#!/bin/bash

echo "Installing python3.2..."
sudo apt-get install python3.2 pip3
#sudo apt-get install python3 python3-pip

echo "Installing PostgreSQL version >= 9.3..."
echo -e "\t Do it by hand and press <Enter>"
read

echo "Setting virtualenv..."
#sudo apt-get install python-virtualenv
mkdir ~/.virtualenvs/
cd ~/.virtualenvs/
virtualenv -p python3.2 flask3
#virtualenv -p python3 flask3
source flask3/bin/activate

echo "Setting hot commands..."
echo "alias activate_flask3='source ~/.virtualenvs/flask3/bin/activate'" >> ~/.bashrc

echo "Installing plugins for Python..."
#sudo apt-get install python3.2-dev
pip3 install flask
# pip3 install pymongo
pip3 install psycopg2

echo "for flask:"
pip3 install flask flask-wtf
pip3 install sqlalchemy
pip3 install sqlalchemy-migrate
pip3 install flask-sqlalchemy
pip3 install flask-login

